# Nylo - Micro-framework for Flutter.
#
# Website: https://nylo.dev
# Official repository: https://github.com/nylo-core/nylo
# Author: Anthony Gordon <https://github.com/agordn52>

name: taco_stack_app
description: the app allows users to fill out weekly reports and daily standup.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=3.24.0 <4.0.0"
dependencies:
  dartz: ^0.10.1
  url_launcher: ^6.2.6
  google_fonts: ^6.2.1
  analyzer: ^7.3.0
  intl: ^0.19.0
  nylo_framework: ^6.6.1
  pretty_dio_logger: ^1.4.0
  cupertino_icons: ^1.0.8
  path_provider: ^2.1.4
  flutter_local_notifications: ^18.0.1
  font_awesome_flutter: ^10.8.0
  scaffold_ui: ^1.1.7
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  supabase_flutter: ^2.8.2
  gap: ^3.0.1
  json_annotation: ^4.9.0
  json_serializable: ^6.9.0
  flutter_bloc: ^9.0.0
  hydrated_bloc: ^10.0.0
  freezed: ^2.5.7
  app_settings: ^5.1.1

dev_dependencies:
  rename: ^3.0.2
  flutter_launcher_icons: ^0.14.1
  # The following line 'flutter_lints' activates a set of recommended lints for Flutter apps,
  # packages, and plugins designed to encourage good coding practices.
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.14
  flutter_gen_runner: ^5.8.0

# APP ICON - public/app_icon/icon.png
# Build icons: "dart run flutter_launcher_icons"
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "public/app_icon/icon.png"
  remove_alpha_ios: true

# RENAME YOUR PROJECT
# flutter pub run rename setAppName --targets ios,android --value "YourAppName"

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - public/fonts/
    - public/images/
    - public/images/avatars/
    - public/app_icon/
    - lang/
    - .env

flutter_gen:
  output: lib/src/gen